export const GET_PATIENTS_BY_NAME_CACHE = 'GET_PATIENTS_BY_NAME_CACHE';
export const GET_PATIENT_BY_ID_CACHE = 'GET_PATIENT_BY_ID_CACHE';
export const GET_PATIENT_BODY_EVOLUTION_CACHE = 'GET_PATIENT_BODY_EVOLUTION_CACHE';
export const GET_NUTRITIONIST_INFO = 'GET_NUTRITIONIST_INFO';
